name: CI/CD Deploy
on:
  push:
    branches: [ main ]
# main に push されたら自動で CI/CD が走る

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js v18 をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. ルートと CDK ディレクトリの依存関係インストール
      - name: Install API dependencies
        working-directory: ./api
        run: npm install

      - name: Install CDK dependencies
        working-directory: ./cdk
        run: npm install

      # 4. TypeScript ビルド
      - name: Build TypeScript
        run: |
          npx tsc --project tsconfig.json   
          cd cdk
          npx tsc --project tsconfig.json   
        # API ソースを dist にビルド
        # CDK コードを dist にビルド

      # 5. テスト実行（Jest または任意のテストランナー）
      - name: Run Tests
        run: |
          npx jest        
        # jest が devDependencies にある場合
        continue-on-error: false

      # 6. CDK デプロイ（Lambda Docker イメージ自動作成 + ECR push）
      - name: CDK Deploy
        working-directory: ./cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          npx cdk deploy --require-approval never
