name: Deploy
on:
  push:
    branches: [ main ] # main ブランチへの push で発火

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. コードをチェックアウト
      - uses: actions/checkout@v3

      # 2. Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 依存関係のインストール
      - name: Install dependencies
        run: |
          cd api
          npm install
          cd ../cdk
          npm install

      # 4. ECR にログイン
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 5. Docker イメージのビルド
      - name: Build Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPO }}:latest
          docker build -f api/Dockerfile -t $IMAGE_URI ./api
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # 6. Docker イメージを ECR にプッシュ
      - name: Push Docker image to ECR
        run: docker push ${{ env.IMAGE_URI }}

      # 7. CDK デプロイ
      - name: CDK Deploy
        working-directory: ./cdk
        run: npx cdk deploy --require-approval never -c useExistingRepo=true
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
